### ISSUE TITLE
Need database script

### ISSUE THREAD

**Issue by rokkanen** [Azure-Samples/dab-swa-library-demo#2]
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [X] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```
Hi, 

Miss a link to do how create database with at script ?
I Found the response here:
https://github.com/Azure/data-api-builder/blob/main/samples/getting-started/azure-sql-db/library.azure-sql.sql

THX
😀

**Comment by thomasgauvin** [comment]
Just added, thanks for the ping @rokkanen! Let us know your feedback about the feature, you can add any question/issue here: https://github.com/Azure/static-web-apps/discussions/1111

**Comment by rokkanen** [comment]
Good !
